--- @meta

LibAddonMenu2 = {}
LibDebugLogger = {}
LibFBCommon = {}
LibSavedVars = {}
VOTANS_FISHERMAN = {}

FishBarWindow = {}
RETICLE = {}

ADDITIONAL_INTERACT_INFO_FISHING_NODE = 3
BAG_BACKPACK = 1
BAG_VIRTUAL = 5
NON_COMBAT_BONUS_FISHING_TIME_REDUCTION_PERCENT = 96
SI_CHAT_CHANNEL_NAME_EMOTE = 0
SI_DIALOG_CONFIRM = 0
SI_GAMECAMERAACTIONTYPE17 = 0
SI_GUILDACTIVITYATTRIBUTEVALUE9 = 0
TIMER_BAR_COUNTS_DOWN = 2

FISHBAR_MOVEFRAME = ""
FISHBAR_BAR_COLOUR = ""
FISHBAR_SHOW_LABEL = ""
FISHBAR_LABEL_COLOUR = ""
FISHBAR_EMOTE = ""
FISHBAR_EMOTE_DESC = ""

function ZO_SceneManager_ToggleHUDUIBinding() end
